name: GitHub Codespaces JS devcontainer image

on:
  push:
    branches:
      - main
    paths:
      - 'images/js-devcontainer/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: './images/js-devcontainer/Dockerfile'
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/js-devcontainer:1.0.0-alpine3.14"
          no-cache: true
          push: true

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
